spring:
  datasource:
    url: "jdbc:mysql://127.0.0.1:3306/blog?allowMultiQueries=true&rewriteBatchedStatements=true&useAffectedRows=true&serverTimezone=Asia/Shanghai"
    username: root
    password: toor
    druid.stat-view-servlet:
      login-username: root
      login-password: toor
  redis:
    host: 127.0.0.1
    port: 6379
    username: default
    password: toor
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: root
    password: toor
    virtual-host: /
logging.level:
  top.yinzsw.blog.mapper: debug
springdoc:
  packages-to-scan: top.yinzsw.blog.controller
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: method
openapi:
  title: "博客API文档"
  version: "@project.version@"
  description: "一个基于SpringBoot + Vue3的博客项目"
  contact-name: "yinzsW"
  contact-url: "https://github.com/yinzsw"
  contact-email: "yinzsW@qq.com"