spring:
  application:
    name: blog
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: "@profile.active@"
  servlet:
    multipart:
      max-file-size: 32MB
      max-request-size: 64MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      async-init: true
      initial-size: 5   #初始化连接池数量
      min-idle: 5       #最小连接池数量
      max-active: 20    #最大连接池数量
      max-wait: 6000    #取连接的超时等待时间(ms)
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      filters: mergeStat
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
        session-stat-enable: true
        session-stat-max-count: 1000
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
  redis:
    database: 0
    lettuce.pool:
      enabled: true
      min-idle: 5
      max-idle: 16
      max-active: 16
      max-wait: 3000ms
      time-between-eviction-runs: 1s
  rabbitmq:
    listener:
      simple:
        prefetch: 1
  mail:
    host: smtp.qq.com
    port: 465
    username: ${MAIL.USERNAME}
    password: ${MAIL.PASSWORD}
    default-encoding: UTF-8
    protocol: smtp
    properties:
      auth: true
      mail.smtp.ssl.enable: true
feign:
  httpclient:
    enabled: true
  client:
    config:
      default:
        read-timeout: 5000
        connect-timeout: 5000
        logger-level: basic
upload:
  mode: local
  bucket: ${UPLOAD.BUCKET}
  endpoint: ${UPLOAD.ENDPOINT}
  domain-url: ${UPLOAD.DOMAIN_URL}
  access-key: ${UPLOAD.ACCESS_KEY}
  access-key-secret: ${UPLOAD.ACCESS_KEY_SECRET}
blog:
  jwt-key: ${JWT.KEY}
  initialization: true

